include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LiquidLock26Prefs

LiquidLock26Prefs_FILES = LL26RootListController.m
LiquidLock26Prefs_FRAMEWORKS = UIKit
LiquidLock26Prefs_INSTALL_PATH = /Library/PreferenceBundles
LiquidLock26Prefs_CFLAGS = -fobjc-arc
LiquidLock26Prefs_LDFLAGS = -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
